/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multicine;

import javax.swing.JOptionPane;

/**
 *
 * @author Fran
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    
    SalaCine central;
    SalaCine vo;
    
    public VentanaPrincipal() {
        initComponents();
        
        central=new SalaCine();
        vo=new SalaCine();
        
        central.setAforo(500);
        central.setEntrada(8.0);
        
        vo.setAforo(80);
        vo.setEntrada(6.0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCentral = new javax.swing.JLabel();
        labelTituloCentral = new javax.swing.JLabel();
        txtCentral = new javax.swing.JTextField();
        btnCambiarCentral = new javax.swing.JButton();
        btnVentaCentral = new javax.swing.JButton();
        btnOcupacionCentral = new javax.swing.JButton();
        btnVaciarCentral = new javax.swing.JButton();
        btnIngresosCentral = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelOriginal = new javax.swing.JLabel();
        labelTituloOriginal = new javax.swing.JLabel();
        txtOriginal = new javax.swing.JTextField();
        btnCambiarOriginal = new javax.swing.JButton();
        btnVentaOriginal = new javax.swing.JButton();
        btnOcupacionOriginal = new javax.swing.JButton();
        btnVaciarOriginal = new javax.swing.JButton();
        btnIngresosOriginal = new javax.swing.JButton();
        btnIngresosTotales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCentral.setText("Película");

        labelTituloCentral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTituloCentral.setText("SALA CENTRAL");

        txtCentral.setEditable(false);

        btnCambiarCentral.setText("Cambiar");
        btnCambiarCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarCentralActionPerformed(evt);
            }
        });

        btnVentaCentral.setText("Nueva Venta");
        btnVentaCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaCentralActionPerformed(evt);
            }
        });

        btnOcupacionCentral.setText("% Ocupación");
        btnOcupacionCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcupacionCentralActionPerformed(evt);
            }
        });

        btnVaciarCentral.setText("Vaciar");
        btnVaciarCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarCentralActionPerformed(evt);
            }
        });

        btnIngresosCentral.setText("Ingresos");
        btnIngresosCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosCentralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCentral)
                        .addGap(18, 18, 18)
                        .addComponent(txtCentral)
                        .addGap(18, 18, 18)
                        .addComponent(btnCambiarCentral)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTituloCentral)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVentaCentral)
                                .addGap(18, 18, 18)
                                .addComponent(btnOcupacionCentral)
                                .addGap(18, 18, 18)
                                .addComponent(btnVaciarCentral)
                                .addGap(18, 18, 18)
                                .addComponent(btnIngresosCentral)))
                        .addContainerGap(93, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloCentral)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCentral)
                    .addComponent(txtCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarCentral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVentaCentral)
                    .addComponent(btnOcupacionCentral)
                    .addComponent(btnVaciarCentral)
                    .addComponent(btnIngresosCentral))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelOriginal.setText("Película");

        labelTituloOriginal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTituloOriginal.setText("SALA VERSION ORIGINAL");

        txtOriginal.setEditable(false);

        btnCambiarOriginal.setText("Cambiar");

        btnVentaOriginal.setText("Nueva Venta");

        btnOcupacionOriginal.setText("% Ocupación");

        btnVaciarOriginal.setText("Vaciar");

        btnIngresosOriginal.setText("Ingresos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelOriginal)
                        .addGap(18, 18, 18)
                        .addComponent(txtOriginal)
                        .addGap(18, 18, 18)
                        .addComponent(btnCambiarOriginal)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTituloOriginal)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnVentaOriginal)
                                .addGap(18, 18, 18)
                                .addComponent(btnOcupacionOriginal)
                                .addGap(18, 18, 18)
                                .addComponent(btnVaciarOriginal)
                                .addGap(18, 18, 18)
                                .addComponent(btnIngresosOriginal)))
                        .addContainerGap(93, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloOriginal)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOriginal)
                    .addComponent(txtOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarOriginal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVentaOriginal)
                    .addComponent(btnOcupacionOriginal)
                    .addComponent(btnVaciarOriginal)
                    .addComponent(btnIngresosOriginal))
                .addContainerGap())
        );

        btnIngresosTotales.setText("Ingresos Totales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresosTotales)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngresosTotales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarCentralActionPerformed
        String titulo;
        titulo=JOptionPane.showInputDialog(null, "Introduzca título para la película: ");
        central.setPelicula(titulo);
        txtCentral.setText(titulo);
    }//GEN-LAST:event_btnCambiarCentralActionPerformed

    private void btnVentaCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaCentralActionPerformed
       central.entraUno();
    }//GEN-LAST:event_btnVentaCentralActionPerformed

    private void btnOcupacionCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcupacionCentralActionPerformed
        String info;
        
        info= "Sala Central";
        info=info+"\nPelícula: "+central.getPelicula();
        info=info+"\nAforo: "+central.getAforo();
        info=info+"\nOcupadas: "+central.getOcupadas();
        info=info+"\nLibres: "+central.getLibres();
        info=info+"\nPorcentaje de Ocupación: "+central.getPorcentaje();
        
        JOptionPane.showMessageDialog(null, info);
    }//GEN-LAST:event_btnOcupacionCentralActionPerformed

    private void btnVaciarCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarCentralActionPerformed
        central.Vaciar();
        txtCentral.setText("");
    }//GEN-LAST:event_btnVaciarCentralActionPerformed

    private void btnIngresosCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosCentralActionPerformed
       String info;
       
       info="Ingresos de la sala: "+central.getIngresos()+"€";
       JOptionPane.showMessageDialog(null, info);
    }//GEN-LAST:event_btnIngresosCentralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarCentral;
    private javax.swing.JButton btnCambiarOriginal;
    private javax.swing.JButton btnIngresosCentral;
    private javax.swing.JButton btnIngresosOriginal;
    private javax.swing.JButton btnIngresosTotales;
    private javax.swing.JButton btnOcupacionCentral;
    private javax.swing.JButton btnOcupacionOriginal;
    private javax.swing.JButton btnVaciarCentral;
    private javax.swing.JButton btnVaciarOriginal;
    private javax.swing.JButton btnVentaCentral;
    private javax.swing.JButton btnVentaOriginal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCentral;
    private javax.swing.JLabel labelOriginal;
    private javax.swing.JLabel labelTituloCentral;
    private javax.swing.JLabel labelTituloOriginal;
    private javax.swing.JTextField txtCentral;
    private javax.swing.JTextField txtOriginal;
    // End of variables declaration//GEN-END:variables
}
