/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IE351;

/**
 *
 * @author Ever
 */
public class Ejercicio11 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio11
     */
    public Ejercicio11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comidas = new javax.swing.ButtonGroup();
        radCocido = new javax.swing.JRadioButton();
        radLentejas = new javax.swing.JRadioButton();
        radJudias = new javax.swing.JRadioButton();
        chkLentejas = new javax.swing.JCheckBox();
        chkChorizo = new javax.swing.JCheckBox();
        chkCebolla = new javax.swing.JCheckBox();
        chkGarbanzos = new javax.swing.JCheckBox();
        chkMorcilla = new javax.swing.JCheckBox();
        chkZanahoria = new javax.swing.JCheckBox();
        chkJudias = new javax.swing.JCheckBox();
        chkColorante = new javax.swing.JCheckBox();
        chkPescado = new javax.swing.JCheckBox();
        chkNuezMoscada = new javax.swing.JCheckBox();
        chkLaurel = new javax.swing.JCheckBox();
        chkPimenton = new javax.swing.JCheckBox();
        btnComprobar = new javax.swing.JButton();
        etiResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chef 4000");

        comidas.add(radCocido);
        radCocido.setText("Cocido");
        radCocido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCocidoActionPerformed(evt);
            }
        });

        comidas.add(radLentejas);
        radLentejas.setText("Lentejas");

        comidas.add(radJudias);
        radJudias.setText("Judías");

        chkLentejas.setText("Lentejas");

        chkChorizo.setText("Chorizo");

        chkCebolla.setText("Cebolla");

        chkGarbanzos.setText("Garbanzos");

        chkMorcilla.setText("Morcilla");

        chkZanahoria.setText("Zanahoria");

        chkJudias.setText("Judías");

        chkColorante.setText("Colorante");

        chkPescado.setText("Pescado");

        chkNuezMoscada.setText("Nuez moscada");

        chkLaurel.setText("Laurel");

        chkPimenton.setText("Pimentón");
        chkPimenton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPimentonActionPerformed(evt);
            }
        });

        btnComprobar.setText("Comprobar");
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkChorizo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkCebolla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkLentejas, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkGarbanzos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(chkZanahoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addComponent(chkMorcilla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkColorante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(chkJudias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkNuezMoscada)
                            .addComponent(chkLaurel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(chkPescado, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkPimenton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(radCocido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radLentejas)
                .addGap(56, 56, 56)
                .addComponent(radJudias)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(etiResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnComprobar))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCocido)
                    .addComponent(radLentejas)
                    .addComponent(radJudias))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLentejas)
                    .addComponent(chkGarbanzos)
                    .addComponent(chkJudias)
                    .addComponent(chkNuezMoscada))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkChorizo)
                    .addComponent(chkMorcilla)
                    .addComponent(chkColorante)
                    .addComponent(chkLaurel))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCebolla)
                    .addComponent(chkZanahoria)
                    .addComponent(chkPescado)
                    .addComponent(chkPimenton))
                .addGap(18, 18, 18)
                .addComponent(btnComprobar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radCocidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCocidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radCocidoActionPerformed

    private void chkPimentonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPimentonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPimentonActionPerformed

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        if(radCocido.isSelected()){
            if(chkChorizo.isSelected()&&
                    chkMorcilla.isSelected()&&
                    chkGarbanzos.isSelected()&&
                    chkZanahoria.isSelected()){
                if((!chkLentejas.isSelected())&&
                        (!chkCebolla.isSelected())&&
                        (!chkJudias.isSelected())&&
                        (!chkColorante.isSelected())&&
                        (!chkPescado.isSelected())&&
                        (!chkNuezMoscada.isSelected())&&
                        (!chkLaurel.isSelected())&&
                        (!chkPimenton.isSelected())){
                    etiResultado.setText("Correcto");
                }else{
                    etiResultado.setText("Incorrecto");
                }
            }else{
                etiResultado.setText("Incorrecto");
            }
        }else if(radLentejas.isSelected()){
            if(chkChorizo.isSelected()&&
                    chkLentejas.isSelected()&&
                    chkCebolla.isSelected()&&
                    chkZanahoria.isSelected()&&
                    chkPimenton.isSelected()){
                if((!chkGarbanzos.isSelected())&&
                        (!chkMorcilla.isSelected())&&
                        (!chkJudias.isSelected())&&
                        (!chkColorante.isSelected())&&
                        (!chkPescado.isSelected())&&
                        (!chkNuezMoscada.isSelected())&&
                        (!chkLaurel.isSelected())){
                    etiResultado.setText("Correcto");
                }else{
                    etiResultado.setText("Incorrecto");
                }
            }else{
                etiResultado.setText("Incorrecto");
            }
        }else if(radJudias.isSelected()){
            if(chkChorizo.isSelected()&&
                    chkCebolla.isSelected()&&
                    chkJudias.isSelected()&&
                    chkColorante.isSelected()&&
                    chkNuezMoscada.isSelected()&&
                    chkLaurel.isSelected()){
                if((!chkLentejas.isSelected())&&
                        (!chkGarbanzos.isSelected())&&
                        (!chkMorcilla.isSelected())&&
                        (!chkZanahoria.isSelected())&&
                        (!chkPimenton.isSelected())&&
                        (!chkPescado.isSelected())){
                    etiResultado.setText("Correcto");
                }else{
                    etiResultado.setText("Incorrecto");
                }
            }else{
                etiResultado.setText("Incorrecto");
            }
        }else{
            
        }
    }//GEN-LAST:event_btnComprobarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobar;
    private javax.swing.JCheckBox chkCebolla;
    private javax.swing.JCheckBox chkChorizo;
    private javax.swing.JCheckBox chkColorante;
    private javax.swing.JCheckBox chkGarbanzos;
    private javax.swing.JCheckBox chkJudias;
    private javax.swing.JCheckBox chkLaurel;
    private javax.swing.JCheckBox chkLentejas;
    private javax.swing.JCheckBox chkMorcilla;
    private javax.swing.JCheckBox chkNuezMoscada;
    private javax.swing.JCheckBox chkPescado;
    private javax.swing.JCheckBox chkPimenton;
    private javax.swing.JCheckBox chkZanahoria;
    private javax.swing.ButtonGroup comidas;
    private javax.swing.JLabel etiResultado;
    private javax.swing.JRadioButton radCocido;
    private javax.swing.JRadioButton radJudias;
    private javax.swing.JRadioButton radLentejas;
    // End of variables declaration//GEN-END:variables
}
