/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package IE351;

/**
 *
 * @author Alumno
 */
public class Ejercicio02 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio02
     */
    public Ejercicio02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiFor1 = new javax.swing.JLabel();
        etiEspacio1 = new javax.swing.JLabel();
        etiTiempo1 = new javax.swing.JLabel();
        etiVelocidad1 = new javax.swing.JLabel();
        txtEspacio1 = new javax.swing.JTextField();
        txtTiempo1 = new javax.swing.JTextField();
        etiRes1 = new javax.swing.JLabel();
        etiFor2 = new javax.swing.JLabel();
        etiVelocidad2 = new javax.swing.JLabel();
        etiTiempo2 = new javax.swing.JLabel();
        etiEspacio2 = new javax.swing.JLabel();
        txtVelocidad2 = new javax.swing.JTextField();
        txtTiempo2 = new javax.swing.JTextField();
        etiRes2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiFor1.setText("V=S/t");

        etiEspacio1.setText("Espacio:");

        etiTiempo1.setText("Tiempo:");

        etiVelocidad1.setText("Velocidad:");

        txtEspacio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspacio1ActionPerformed(evt);
            }
        });

        txtTiempo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempo1ActionPerformed(evt);
            }
        });

        etiFor2.setText("S=V*t");

        etiVelocidad2.setText("Velocidad:");

        etiTiempo2.setText("Tiempo:");

        etiEspacio2.setText("Espacio:");

        txtVelocidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVelocidad2ActionPerformed(evt);
            }
        });

        txtTiempo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiVelocidad1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(etiTiempo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiEspacio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiFor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEspacio1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtTiempo1)
                    .addComponent(etiRes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiFor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiVelocidad2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(etiTiempo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiEspacio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVelocidad2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtTiempo2)
                    .addComponent(etiRes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiFor1)
                    .addComponent(etiFor2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiEspacio1)
                    .addComponent(txtEspacio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiVelocidad2)
                    .addComponent(txtVelocidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiTiempo1)
                    .addComponent(txtTiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiTiempo2)
                    .addComponent(txtTiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiVelocidad1)
                        .addComponent(etiRes1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiEspacio2)
                        .addComponent(etiRes2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEspacio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspacio1ActionPerformed
        etiRes1.setText((Double.parseDouble(txtEspacio1.getText())/
                (Double.parseDouble(txtTiempo1.getText())))+"");
    }//GEN-LAST:event_txtEspacio1ActionPerformed

    private void txtTiempo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempo1ActionPerformed
        etiRes1.setText((Double.parseDouble(txtEspacio1.getText())/
                (Double.parseDouble(txtTiempo1.getText())))+"");
    }//GEN-LAST:event_txtTiempo1ActionPerformed

    private void txtVelocidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVelocidad2ActionPerformed
        etiRes2.setText((Double.parseDouble(txtVelocidad2.getText())*
                (Double.parseDouble(txtTiempo2.getText())))+"");
    }//GEN-LAST:event_txtVelocidad2ActionPerformed

    private void txtTiempo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempo2ActionPerformed
        etiRes2.setText((Double.parseDouble(txtVelocidad2.getText())*
                (Double.parseDouble(txtTiempo2.getText())))+"");
    }//GEN-LAST:event_txtTiempo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiEspacio1;
    private javax.swing.JLabel etiEspacio2;
    private javax.swing.JLabel etiFor1;
    private javax.swing.JLabel etiFor2;
    private javax.swing.JLabel etiRes1;
    private javax.swing.JLabel etiRes2;
    private javax.swing.JLabel etiTiempo1;
    private javax.swing.JLabel etiTiempo2;
    private javax.swing.JLabel etiVelocidad1;
    private javax.swing.JLabel etiVelocidad2;
    private javax.swing.JTextField txtEspacio1;
    private javax.swing.JTextField txtTiempo1;
    private javax.swing.JTextField txtTiempo2;
    private javax.swing.JTextField txtVelocidad2;
    // End of variables declaration//GEN-END:variables
}
